name: Build, Test, and Package

on: workflow_dispatch
  #push:
    #branches:
      #- main  
  #pull_request:
    #branches:
      #- main  

jobs:
  run-make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Makefile
        run: |
          cd ~/cicd
          make 

  run-test:
    runs-on: ubuntu-latest
    needs: run-make  
    steps:
      - name: Run test
        run: |
          cd ~/usr/bin
          ./test
          if [ $? -eq 0 ]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
            exit 1
          fi

  run-packaging:
    runs-on: ubuntu-latest
    needs: run-test  
    if: needs.run-test.outputs.status == 'success'  
    steps:
      - name: Install dpkg utilities
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev build-essential

      - name: Create .deb package
        run: 
          dpkg-deb --build 


