name: Build, Test, and Package

on: workflow_dispatch
  #push:
    #branches:
      #- main  
  #pull_request:
    #branches:
      #- main  

jobs:
  run-make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Makefile
        run: |
          cd ./cicd
          make 
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: | 
            ./bin
            test

  run-test:
    runs-on: ubuntu-latest
    needs: run-make  
    outputs:
      status: ${{ steps.test.outputs.status }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build
      - name: Make test executable
        run: chmod +x ./build/bin/test
      - name: Run test
        id: test
        run: |
          cd ./build
          ./bin/test
          if [ $? -eq 0 ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

  run-packaging:
    runs-on: ubuntu-latest
    needs: run-test  
    if: needs.run-test.outputs.status == 'success'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build
          
      - name: Install dpkg utilities
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev build-essential

      - name: Create .deb package
        run: 
          dpkg-deb --build
          
      - name: Upload .deb package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ./


